### ISSUE TITLE
Addons loaded, but non-functional ingame.

### ISSUE THREAD

**Issue by fanonwue** [gw2-addon-loader/loader-core#10]
I've used the UOAM to update stuff today. It only updated the addon loader. After this update, no addon is functional ingame. The log clearly states that the addons are loaded (I've checked the file's timestamp), but they just aren't present ingame. I've used the Addon Manager and this addon loader for over a year without problems, but for some reason the addons don't appear ingame anymore.
```
[INFO] core | Addon loader v1.0 (v1.1 r33) initialized
[INFO] core | Loading addons from "./addons" path
[INFO] core | Loading arcdps
[INFO] core | Loaded d3d9_wrapper v2.0 r21
[INFO] core | Loaded arcdps v1.0 r480
[INFO] core | Loading d3d9_wrapper
[INFO] core | Loading gw2radial
[INFO] core | Loaded gw2radial v2.2 r1
[INFO] core | Loading logs
[ERR] core | addons/logs/gw2addon_logs.dll not found
[INFO] core | Done loading addons
[INFO] d3d9_wrapper | Loading system d3d11
```
ArcDPS and all plugins I've installed for it load perfectly fine when going with the "d3d11.dll" route.

**Comment by knoxfighter** [comment]
This is caused by a changed loading order when using CEF.
You should have the `dxgi.dll` in two places: Next to the gw2 executable and in `/bin64/cef`.
So, copy it from one place to the other one.

**Comment by fanonwue** [comment]
Thanks a lot for this tip! It works now. Don't know what happened to the `dxgi.dll` next to the executable though...
