### ISSUE TITLE
Better install instructions

### ISSUE THREAD

**Issue by Friendly0Fire** [gw2-addon-loader/loader-core#4]

**Comment by EstebPain** [comment]
Hello! I was going to make a post about something related, might as well leave it here ^^

When following the manual instructions to install radial, it states "Install the addon loader and d3d wrapper."
My only thought was to download the github project, unzip and leave in addon folder, but it isn't working.
How should I install both of those? I couldn't find instructions in google nor in reddit, and the proper projects github doesn't have a how-to-install.

------
Thank you, and really good work here ñ_ñ I like it very much
