### ISSUE TITLE
Arcdps not loaded 

### ISSUE THREAD

**Issue by ChristophDl** [gw2-addon-loader/loader-core#9]
I have placed
bin64, addonLoader.dll, d3d11.dll, dxgi.dll in my GW2 installation directory and, in there, have created a folder addons/arcdps. Then I downloaded the newest d3d11.dll for arcdps, renamed it to gw2addon_arcdps.dll and placed it in that folder. However, when starting GW2, arcdps is unavailable.

Please let me know in case you need any log files. Thanks!

**Comment by knoxfighter** [comment]
The addon loader is not supposed to be setup manually. Please use the addon manager (UOAOM) for the initial setup. You don't have to use the manager after that and you can work manually with the installed files, but the first setup should be done with it.
